### PR TITLE
Updated TransactionStatusDTO code

### PR DESCRIPTION
**Pull request by dgarcia360**

### CODE REVIEW

**Comment by dgarcia360** [comment]
Related https://github.com/nemtech/catapult-rest/issues/230

**Comment by fboucquez** [comment]
Is it better for a user perspective to just have the int code? What about a nice description text?
Why is code a string and not a number?

**Comment by Vektrat** [comment]
we just kept it the way it was done, and it's not really users, but devs, not sure why string, to support hex maybe?

either way i was trying to improve errors in REST overall the past 2 weeks but it's not trivial with the library we're currently using, and i wanted to avoid going through a full rehaul of the project, but i'm still looking what can i do to provide better error objects, specially to remove erroring variables from within error string descriptions

anyway, in this kind of errors a nice description probably won't be happening, because those are fetched straight from mongodb and delivered to the clients

**Comment by fboucquez** [comment]
A code like  `-2141913081` is not very useful if there is no dictionary that tells the meaning of that number. That can be 1) Documented in a written table somewhere AND/OR 2) Mapped in rest <int,string>

In rest, you can add new fields (like status resolved from the map <int,string>) before returning the object via rest endpoint and web socket right?  

if I (or any client) just see a number, I would be wasting time trying to figuring out what that number means.

**Comment by Vektrat** [comment]
a code like `-2141913081` is not what REST should be returning, this is a bug due to an unannounced mongdb schema update and this is the origin of this task to begin with... REST supposedly returns error strings as it always has and as it still is doing https://github.com/nemtech/catapult-rest/pull/232/files#diff-8f5041a7954fdc8106e46d570bab079aR104

**Comment by fboucquez** [comment]
If rest doesn't translate it will be up to the users/sdks to have the transaction table up to date. Many more places to change if a code is added, removed or updated

**Comment by Vektrat** [comment]
i'm not sure where all this is coming from, those status codes were resolved and should be resolved again with yesterday's fix - and the resolution is a string

**Comment by rg911** [comment]
> i'm not sure where all this is coming from, those status codes were resolved and should be resolved again with yesterday's fix - and the resolution is a string

I think @fboucquez is talking about this: https://nemtech.github.io/api.html#status-errors

**Comment by fboucquez** [comment]
> > i'm not sure where all this is coming from, those status codes were resolved and should be resolved again with yesterday's fix - and the resolution is a string
> 
> I think @fboucquez is talking about this: https://nemtech.github.io/api.html#status-errors

I'm just saying that a text like `Failure_Core_Too_Many_Transactions` should appear in the returned JSON objects and not just the numeric code.

**Comment by Vektrat** [comment]
> > > i'm not sure where all this is coming from, those status codes were resolved and should be resolved again with yesterday's fix - and the resolution is a string
> > 
> > 
> > I think @fboucquez is talking about this: https://nemtech.github.io/api.html#status-errors
> 
> I'm just saying that a text like `Failure_Core_Too_Many_Transactions` should appear in the returned JSON objects and not just the numeric code.

and where is it not being returned like so that is not a bug?

**Comment by dgarcia360** [comment]
I just added a new commit documenting better to the DTO by creating a command-line script to generate the  ``TransactionStatusCodeEnum`` docs automatically. After the festivities, I'll refine the script and publish it so that anyone can run it.

Besides, we have noticed with @Vektrat that the endpoint might still be using the status field for confirmed and unconfirmed transactions.  I'll postpone merging this PR until the behavior is clear / fixed. Ideally, it should use ``status`` or ``code`` for either confirmed, unconfirmed, and failed transactions.

@rg911 @fboucquez After testing the endpoint,  ``code`` is returning the text version of the status error. I think it would be good as well to return both, if possible. Let's try to close this PR, and then we can create a new PR proposal if the number version of the error is still necessary.

**Comment by dgarcia360** [comment]
Fixed with https://github.com/nemtech/catapult-rest/commit/50cdbde25d49717dd0fa1114fa798bb2d6706bcc 

Please, review again this PR before merging it.

**Pull request merged**
