### PR TITLE
Added network type name enum

### LINKED ISSUE #43: NetworkTypeDTO's name attribute should be a Enum.
Hi @dgarcia360 

I've revisited one of the endpoints. I want to map the possible string values of http://localhost:3000/network to the NetworkType enums we use. 

At the moment, open API doesn't specify those values, just the mijinTest example. Would it possible to add all the examples or even better change the name type to enum? It's hard to tell which are the expected values from other networks.

The workaround is using /node/info endpoint to know easily know the network type.

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes #43

### CODE REVIEW

**Comment by fboucquez** [comment]
Should we update the version from 0.7.19 to 0.7.20? How can we tell that a version has been released and it's not dev mode? Java already released 0.7.19 generated clients, any change will be part of another version, I can call it 0.7.20 or 0.7.19.1 though

**Comment by dgarcia360** [comment]
We are trying to keep this repo versioned as the catapult-rest repo (https://github.com/nemtech/nem2-openapi/releases). Right now we can merge this into master branch, and as soon as the next catapult-rest version is released we will add a new PR changing the version number.

**Comment by fboucquez** [comment]
Ok, I'm assuming the next version of catapult-rest and this open API is the 0.7.20. 

0.7.19 has been released in all 3 rest, open API and generated clients

**Comment by Vektrat** [comment]
i can approve this but should the network name be an structural enum of the project? isn't it more of a configuration parameter rather than an option?

**Comment by fboucquez** [comment]
Good question. I'm not sure. Where is that value coming from? Is it
possible to have the same numeric network type with different name?

The string comparison was hardcover in the Java SDK giving the impression
that the value is a enum not a free text.

**Comment by dgarcia360** [comment]
Initially thought that it was free text, but then found this test: [NetworkInfo_spec.ts](https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/test/model/networkInfo_spec.js#L31).

**Pull request merged**
