### PR TITLE
Proposed mosaic owned endpoints

### PR DESCRIPTION
**Pull request by dgarcia360**
Proposal for https://github.com/nemtech/catapult-rest/issues/11

### CODE REVIEW

**Comment by Vektrat** [comment]
can we remove pagination from this endpoint? i don't think it makes much sense here, and paging is always troublesome ^^

**Comment by Vektrat** [comment]
> can we remove pagination from this endpoint? i don't think it makes much sense here, and paging is always troublesome ^^

@dgarcia360 ^^

**Comment by dgarcia360** [comment]
The equivalent endpoint for owned namespace supports pagination: https://nemtech.github.io/endpoints.html#operation/getNamespacesFromAccount

**Comment by Vektrat** [comment]
in the end we will be implementing this endpoint without pagination, the reasons are as follows:

- that namespaces is paginated does not imply mosaics needs to be, i agree that it's a similar situation, but i still think there's no clear necessity for those two resources to be paginated
- i believe pagination, unless clear, should be implemented on demand after it has been deemed a necessity (performance issues)
- implementation with pagination is not straightforward at all, and would imply dirty technical implementations, because it oringinaly was designed by few endpoints (as i said, i only see a clear need of pagination for transactions) - with the issue being mosaics have no `meta` with containing `id`
- we take note on the pagination limitations and strongly consider refactoring it for similar future and past features (even this one)

**Comment by dgarcia360** [comment]
@Vektrat Have removed pagination, please confirm if the schema proposed matches the implemented endpoint.

**Comment by Vektrat** [comment]
> @Vektrat Have removed pagination, please confirm if the schema proposed matches the implemented endpoint.

@martinayora

**Comment by martinayora** [comment]
The schema matches the implementation in everything but a mosaic key wrapping the mosaic in the response payload.

Proposed response
```
[
  {
    "mosaic": {
      "id": "0DC67FBE1CAD29E3",
      "supply": "string",
...
```
Implemented endpoint
```
[
    {
        "id": "26514E2A1EF33824",
        "supply": "15000000",
```
Because mosaics doesn't have "meta" section, at least for now, there is no mosaic keyword in the database. I guess we can add it if needed.

**Comment by dgarcia360** [comment]
Documented https://github.com/nemtech/catapult-rest/pull/191 and https://github.com/nemtech/catapult-rest/pull/189, please @Vektrat and @martinayora review the open-api changes.

**Comment by martinayora** [comment]
Namespaces output is missing meta section and the namespace wrapper:

openApi output:

```
{
  "namespaces": [
    {
      "registrationType": 0,
      "depth": 1,
      "level0": "85BBEA6CC462B244",
      "level1": "85BBEA6CC462B244",
      "level2": "85BBEA6CC462B244",
      "alias": {
        "type": 0,
        "mosaicId": "0DC67FBE1CAD29E3",
        "address": "9081FCCB41F8C8409A9B99E485E0E28D23BD6304EF7215E01A"
      },
      "parentId": "85BBEA6CC462B244",
      "ownerPublicKey": "AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26",
      "ownerAddress": "9081FCCB41F8C8409A9B99E485E0E28D23BD6304EF7215E01A",
      "startHeight": 1,
      "endHeight": 1
    }
  ]
}
```
rest output:

```
{
    "namespaces": [
        {
            "meta": {
                "active": true,
                "index": 0,
                "id": "5DB333E4B531685D496B0A3D"
            },
            "namespace": {
                "registrationType": 1,
                "depth": 2,
                "level0": "B1497F5FBA651B4F",
                "level1": "941299B2B7E1291C",
                "alias": {
                    "type": 1,
                    "mosaicId": "26514E2A1EF33824"
                },
                "parentId": "B1497F5FBA651B4F",
                "ownerPublicKey": "B4F12E7C9F6946091E2CB8B6D3A12B50D17CCBBF646386EA27CE2946A7423DCF",
                "ownerAddress": "9022D04812D05000F96C283657B0C17990932BC84926CDE64F",
                "startHeight": "1",
                "endHeight": "18446744073709551615"
            }
        }
    ]
}
```

Everything else seems fine.

**Comment by dgarcia360** [comment]
@martinayora :+1: updated

**Pull request merged**
