### PR TITLE
Added f2 changes

### LINKED ISSUE #45: Apply Fushicho2 changes
https://github.com/nemtech/catbuffer/tree/fushicho2

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes #45 and #48

### CODE REVIEW

**Comment by fboucquez** [comment]
What's the plan with the catbuffer reserved values? Should they be included in the open api and sdk transaction objects or the user pretty much don't care about them? It's just a private/internal feature/implementation of catbuffer?

**Comment by dgarcia360** [comment]
In my opinion private / internal. It does not provide any value to the end developer to know that there are reserved values at this level.

1. The API is currently filtering what is redundant. We are already doing this when returning arrays : the serialization schema requires the array size to reserve the space in bytes, but the API  returns just the array.
2. Returning ``reserved1 : ""`` looks more confusing than helpful, since it does not indicate the number of reserved bytes.
3. The json response fields are not always ordered as they appear in the schema, if I'm not mistaken. So one can't trust the response directly to get the transaction in serialized form without the help of the catbuffer builders.

**Comment by fboucquez** [comment]
I agree with you David. The same points apply at SDK level. I don't see any
value and it's worse if we do it half way. I would not add those fields at
SDK model level. SDK will just send empty when serialising to catbuffer

**Comment by dgarcia360** [comment]
@fboucquez @rg911 Just added one missing change we missed reported by @martinayora  (restrictionType-> restrictionFlags)

Diff: https://github.com/nemtech/nem2-openapi/compare/a9e66ee1453bb7caf04c7b5c20ff8843cd4a07d9...45-f2

**Pull request merged**
